### ISSUE TITLE
Determine how users will access the new toolkits (versus the old toolkits)

### ISSUE THREAD

**Issue by swwalker** [DukeLearningInnovation/kits#195]
How will people learn about the new toolkits app?
Where will they go to get the URL?
How are we going to distinguish between old and new versions while they co-exist?
How will system notifications be handled (announcements, notifications of maintenance, etc)?

**Comment by swwalker** [comment]
@outten45 , can you document here what some of the variations currently in use are wrt service pages and how other apps are handling (based on our conversation earlier this week)?

Thanks.

**Comment by outten45** [comment]
I think we were talking about whether users would have to login before getting into toolkits. 

Toolkits currently requires login. We could switch toolkits to have a landing page before a user logs in. This would put that landing page into toolkits. For other sites, we have had a landing page be outside of an app and be in a CMS (Drupal). This allows owners to more easily update content and even put up messages.

For example, we could have (of course the domain would actually be different):

toolkits.duke.edu - this could be the landing site served by the CMS
app.toolkits.duke.edu - this could be the actually application when they click on "login" from the loading site

Does that make sense?

**Comment by profmikegreene** [comment]
Is it possible to detect if a shib session is already active from users visiting another site and if so direct already logged in users to app.toolkits.duke.edu?  I could see returning users really valuing that.

**Comment by outten45** [comment]
That is a little tricky. We have talked with our IDM folks about this before and we weren't able to do that with other sites. The problem is the SP (this case, the landing site) would need to know if the user had an active session with the IdP (shib.oit.duke.edu) and the way to do that is to redirect them to the IdP and check. At that point, they would probably be asked to log in if they hadn't already. 

There was another approach that IDM mentioned, but if I remember right, it sounded like kind of a bigger change for shib. I can ask about that one again.

Another option might be to set a cookie when someone visits app.toolkits.duke.edu that tells the toolkits.duke.edu to site to redirect them automatically. It wouldn't necessarily know if they had to re-authenticate, but it would save them a step in clicking. We might want to think about that one some more - there could be some strangeness that I'm not thinking of at the moment.
