### ISSUE TITLE
Manage Membership Functional decisions

### ISSUE THREAD

**Issue by bap13** [DukeLearningInnovation/kits#197]
Idea floating (based on schedule and vacation constraints) that edits to Manage Members prototype could be made by @noahhh. @swwalker will discuss Thursday. Some functional decisions:

- Page will have auto save
- Waiting until MVP 2 when "bulk add" is created to have the row show up (bulk _remove_ is useless by itself).
- Export Roster exists only in "management" role, and will show all members even if newly "invited"
- Must add name and email type-ahead to Add fields
- "Save" button will be in a disabled state unless something on page changes
- Dropdown roles changed to Visitor, Student, Instructor, Assistant
- If someone who is not in the system is added - there is NO ERROR MESSAGE. They need to manually be removed and re-added
- no pagination, even on a long roster of students will be viewed

**Comment by bap13** [comment]
@swwalker please label with appropriate sprint.

**Comment by LASHirsh** [comment]
adding/expanding on Barbara's notes:

Some functional decisions for MVP1 (note that ideas that should be considered for MVP2 are in the Box note with testing feedback from Sprint 4 testing):

- Page will have auto save (pressing SAVE button will take you to a view-only version of the roster screen with an edit button; pressing the EDIT button will take you back to the editable version of roster) (The EDIT button will be absent from the view-only version of the screen when user a participant/student in the course)
- Students (participants) will only ever see a View version of the screen
- Waiting until MVP 2 when "bulk add" is created to have the "Add another, add many, import..." links row show up 
- Will finish adding bulk edit options, because bulk remove is useless by itself and Will says completing this is easy (note: bulk remove option only shows up if everyone checked was manually added), but we are also okay with adding this is MVP2 if necessary
- Add Export Roster button (this will exist only if user has a "management" role (i.e., instructor) for the course, and the exported roster will show all members even if newly "invited" (there will be a column in the CSV with the status "invited" or "pending" next to those invited people)
- Must add type-ahead to name and email fields
- "Done" button will be in a disabled state unless something on page changes
- Dropdown roles changed to Visitor, Student, Instructor, Assistant
- If someone who is not in the system is added - there is NO ERROR MESSAGE, but you get a modal saying that no results found/the name and email are not in the system, with a prompt to invite person to set up an account with Duke using that email address. 
- If there is a mistake (e.g., the wrong person is added or someone is added with the wrong email address, they need to manually removed and re-added)
- no pagination, even on a long roster of students

**Comment by ewendland23** [comment]
Question 1- there are now 4 roles?  Visitor, Student, Instructor, Assistant.  Can an added member be assigned the role of either Student or Instructor or do those come from the Course roster?  

Question 2 - If, for Question 1, the answer is that an added member can be assigned either the 'Student' or 'Instructor' role, how do we show people that they are not on the official course roster?  Do you think the Registrar might be unhappy calling people not paying for a course, students?

Question 3 - I assume the 'Visitor' role will see the same things the 'Student' role sees when they look at a course?  Ditto for Instructor and Assistant?  

Question 4 - Won't there be cases where someone will need multiple roles?  Example, one of the students in the class is assisting with the Wordpress site, so they need to be an admin.

**Comment by swwalker** [comment]
Per the 7/30 team meeting, additional functional decisions:
- Only the leader/instructor of a community can manage membership.  If an assistant should have that capability, the leader/instructor must assign that individual the instructor role rather than an assistant role.

**Comment by swwalker** [comment]
closed - referenced in #199
