### ISSUE TITLE
cross listed courses - how should they be displayed to students/faculty?

### ISSUE THREAD

**Issue by swwalker** [DukeLearningInnovation/kits#205]

**Comment by chrislorch** [comment]
Just for reference: Here's how this works in Sakai - I wouldn't say this is the ideal process by any means. Occasionally we get a question on how to change a course name after the fact - the user can't do it (we can do it, but it's a policy that we have to be consistent with, especially considering how LTI tools pass course titles, etc it's a bad idea to mess with after the fact).

[Sakai Support: creating a new course or project site](http://sakai-duke.screenstepslive.com/s/sakai_support/m/77292/l/890054-how-do-i-create-a-new-course-or-project-site)

> For cross-listed courses or sites with multiple rosters: choose ONE course in this list that has the most appropriate name for the course site (cannot be changed later).  Additional rosters can be added after the site is created through Site Info, Edit Class Rosters.

If we can reimagine how this works/looks in learn.duke, I think it would be a big help to faculty - otherwise it's probably fine to simply show one of the course titles and have a subheading with the other associated course titles/rosters. This goes hand-in-hand with how sections are displayed.

**Comment by curiousmustard** [comment]
If I'm an instructor, how will the system know to only create a community for one of the cross-listed courses, and not a card for both?

**Comment by profmikegreene** [comment]
Chris said ARTSVIS.115S.01.F18 is a crosslisted course if anyone needs one for research.

**Comment by ewendland23** [comment]
Also, just digging through our SISS data I found that every class indicates fields:
CLASS NBR01
SUBJECT01
CATALOG NBR01
SECTION01
.
.
.
CLASS NBR010
SUBJECT010
CATALOG NBR010
SECTION010

I believe those are the "cross listed" courses for this course.  So we could somehow show that in the Course 'Card'?

**Comment by profmikegreene** [comment]
![img_3174](https://user-images.githubusercontent.com/3632822/43915970-41bf6822-9bda-11e8-8cf6-11367cd10ba1.JPG)
I know my gibberish is illegible, but...

If the right is an example of courses with 1 roster (COMPSCI.101.01.F18 is the prominent title, Intro to computers is sub title). Could we promote Intro to Computers to the prominent title in cross listed courses and have the sub-title be a link that displays a tooltip with all the rosters?

I like the break in the consistency in Card Titles as a way to tell users something is different about this one.

**Comment by LASHirsh** [comment]
met with @curiousmustard and @profmikegreene ...proposal for MVP1 dashboard is to replace the course code with "CROSSLISTED COURSE" and add a menu option to the kit menu "View crosslisting". Selecting this option will open a pop up modal with a list of the crosslisted course codes.

**Comment by LASHirsh** [comment]
On the Manage Roster and View Roster pages, there will need to be a course code badge added for each class that is part of the crosslist group. (See Jen's image below)

@thegreenbot @noahhh , is this feasible? We don't want it to simply say "CROSSLISTED COURSE"  because then there is nothing on the page to indicate what roster you are looking at.

**Comment by curiousmustard** [comment]
Design mockup in Zeplin: https://zpl.io/VQEM7RR
