### ISSUE TITLE
Enable inviting non-Duke individuals to request a OneLink account via email invitation from Kits

### ISSUE THREAD

**Issue by swwalker** [DukeLearningInnovation/kits#302]
I am an instructor trying to add someone not yet affiliated with Duke but can't easily because I have to know Onelink is a thing, go there, and complete the invite process which makes me feel dumb or frustrated.

How might we (the Kits project team) allow instructors to invite people to create a Onelink account and once created add them to the desired kit?

**Questions**

**Assumptions**
- We can actually close the loop and add the newly created Onelink user once they have created their account. This isn't currently possible in Toolkits and would be a major win.

**Hypotheses**

**Comment by ewendland23** [comment]
We already have this logic in Old Toolkits... It actually sends an email to the person etc.  Is this what you mean?

**Comment by profmikegreene** [comment]
Yes @ewendland23 that is the functionality we are referring to. I think the suggestion for a simple `href=mailto` was from one of the testers thinking that would be an quick/easy solution. 

Since we have the "having issues click here for toolkits" link that gives people access to this functionality, I recommend we prioritize adding this to the Kits UI next release.

**Comment by profmikegreene** [comment]
Is our lookup on manage members searching onelink users? I tried searching for bryanagreene@gmail.com which has a onelink account and didn't find her in the lookup.

Can we change the onelink invite email to be from kits instead of toolkits or is that something that'll have to wait until we decomission toolkits?

I didn't go through the onelink user creation process but I did get the email just fine. Since I've always had the page autocomplete for me, I've never noticed this, but I think we should add some indicators on the add user form that state all three fields are required. I initially tested by just putting in an email I knew wasn't in the system and when nothing happened, it took me a second to realize I needed to add name anyway.

**Comment by noahhh** [comment]
I received an email this morning from Mary Mckee regarding this issue.  It sounds like Danai, who I was working with on this, has moved teams and thus will not be working on this issue.  I've let her know where we stand/what we need, so hopefully we can get someone else to help us out with this issue soon.

**Comment by joliet** [comment]
This work is complete, closing.
