### ISSUE TITLE
Timing of deletion of app icon

### ISSUE THREAD

**Issue by swwalker** [DukeLearningInnovation/kits#329]
If a user deletes an app from the course community, the app icon should be removed immediately even if the action is still happening in the background.  No "deleting" state on front end is needed.

**Comment by noahhh** [comment]
@swwalker Could you provide any details as to how I could recreate this issue?

**Comment by swwalker** [comment]
> @swwalker Could you provide any details as to how I could recreate this issue?

Currently unable to recreate in kits-test because it looks like the delete action is no longer working for any app.

issue came out of the testing session on 11/28/18.  @bap13 reported it when deleting an app that had been provisioned for a course.

**Comment by noahhh** [comment]
@swwalker Is this on your account?  I acted as you and removed one from 'Public Speaking, Fall 2018'

However, I have noticed I couldn't remove a Sympa or CIFS due to errors.  Have those been put in a ticket for Liz already?

I also intermittently notice that when I have multiple apps and I remove one, some of the others lose their red trash can badge.  They can still be removed, but the badge disappears and may reappear is another is removed.  Not sure if Will is aware/has a ticket in for this either.
