### ISSUE TITLE
All emails sent from Kits should reference Kits, not Toolkits

### ISSUE THREAD

**Issue by profmikegreene** [DukeLearningInnovation/kits#344]
Replace toolkits with kits in from address, subject, body

**Comment by ewendland23** [comment]
Hi Michael,
Do you have a particular place you are referring to?

Currently we send emails in these cases:
- inviting a Guest
- emailing Panopto admins
- notifying about Sakai Batch Adds
- notifying user if a kit member is not part of Box
- emails to our admins about errors

I think Batch add and guest invitations still should say Toolkits because they come from the old system, right?

toolkits@duke.edu has always been our 'from' address but its bogus and goes to no one.  Do you want to set up a real email account or continue using a bogus one?

Are there other emails we should be sending?

**Comment by swwalker** [comment]
@joliet - please confirm whether this is a Fall 2019, Spring 2020 or other target.  Because emails are sent in different cases, some in functionality in Kits vs Toolkits, I recommend Spring 2020 or later when we have parity with Toolkits and are using Kits as the primary system.
