### ISSUE TITLE
Make it easier to remove/edit apps

### ISSUE THREAD

**Issue by profmikegreene** [DukeLearningInnovation/kits#359]
Folks are clicking the pencil/trashcan icons expecting that to invoke action, can we use a similar pattern to view visibility for edit and remove app and but the pencil/trashcan over the entire icon with some transparency?

**Comment by swwalker** [comment]
Related to reported issue #421

**Comment by swwalker** [comment]
per Ryn Nasser: due to Drupal Enterprise Platform project, this item has been pushed to June.

**Comment by joliet** [comment]
This is an old usability issue that we haven't been able to get resolved.  The issue is that when users chose Edit App fro the kabob menu, the pencil icon appears one each app icon.  Users click the pencil part of the icon but nothing happens.  Just need some minor tweaks so that users can click both the icon and the pencil to get to the edit page.  Jen is aware of this issue as well.
