### ISSUE TITLE
Sakai resource naming strategy for user-created kits

### ISSUE THREAD

**Issue by profmikegreene** [DukeLearningInnovation/kits#390]
Box threw an error email to me because the sakaiws@duke.edu account didn't have a Box account and Kits was trying to add it to Box.

**Comment by ewendland23** [comment]
Hi Michael, can you provide a little more detail?  I assume you are testing on kits-test?  Do you remember which Kit it was?  Thanks!

**Comment by ewendland23** [comment]
Ok, i think I found this.  The root of the problem is this - 

When we create a Sakai Site for a User-Created Kit, Kits does not know what to call that Sakai site.  Currently it names them all "**Sakai Non-SIS Course**"  A real course site would create a name like ITALIAN:335:01:8668:1470

When you add a Sakai site, Kits is checking for a Sakai site with its Sakai name in case its already there.  So for the User-Created kit it is checking for 'Sakai Non-SIS Course'.  It finds https://sakai-test.duke.edu/portal/site/Sakai%20Non-SIS%20Course.  I have no idea when that was set up - it seems like when it was created it must have failed because the sakaiws user was never removed.

The first thing Kits does when it finds a Sakai site that matches is to sync all members of that site to the Kit.  So it brought over sakaiws to your Kit.  That is why you see issues in other resources.  You also would notice him in the Roster - he is Missing, missing since he has no displayname or email. (shouldn't we show at least a netid if those other things are missing?)  Also, you will notice that there is no Sakai site for this kit.  I am guessing it failed to add it because its probably already part of some other site and we currently don't allow duplicates.

So the answer to this problem is for @profmikegreene or @joliet to tell us how to name the Sakai site.  It has to be unique unless they want to connect to an existing Sakai site.  I do have code to check for a user's current project sites...  Not sure what the GUI would look like for that. What do you think?

**Comment by profmikegreene** [comment]
My preference in ranked order below

course | non-course
----------|----------
ITALIAN.335.01.FA19 | CATEGORY.DISPLAYNAME.KitID - COLAB.PYTHON.100.01
ITALIAN.335.01.1470 | CATEGORY.DISPLAYNAME.KIT.KitID - COLAB.PYTHON.KIT.100.01
ITALIAN.335.01.8668.1470 | 

I'd prefer to not use adhoc anywhere if we can get around it with one of the above options or others you think would work better.

Dashes are allowed but I'm not sure about colons. If colons are allowed, i'm ok with them vs the periods in any of the examples above, but my preference for a delimiter would be period since we use that in other places already.

**Comment by noahhh** [comment]
@profmikegreene We should be able to make non-course look close to that.  For displayName - do we have restrictions for what characters they can use?  Do we only allow letters/numbers? 

If the KitId is entered as 100-01, do we change that to 100.01?

Also, I have been putting the Course/Kit ID in the name to allow for them to be unique.  This is the ID that is auto-generated when saved to the DB.   I think we could do something like COLAB.PYTHON.12345.100.01, where 12345 is the DB ID

Going to tag @ewendland23 because she knows a lot of stuff that I don't.

**Comment by noahhh** [comment]
The above naming part is not in this ticket, should be a separate ticket or put on to #126

**Comment by profmikegreene** [comment]
Since the bulk of this naming discussion is here, I'd prefer to continue it here for now and will edit the description of #126 once all questions are answered per @noahhh 's request.

I do not have restrictions from a functional perspective on what characters can be used in display name.

Since we are using 1 field for the Kit ID, I think we'd have to interpret 100-01 as 100-01 for the site title. I don't have any functional restrictions on what characters are allowed in this field other than not allowing whatever delimiter we use between all the sections (period still being my preference).

Adding the DB ID works for me as well, my preference would be to have it at the end.

ITALIAN.335.01.FA19.123245 | CATEGORY.DISPLAYNAME.KitID.DBID - COLAB.PYTHON.100-01.123245
-- | --

**Comment by profmikegreene** [comment]
We just had a Sakai core dev recommend no special characters other than hyphen for the Sakai siteid. I hadn't heard this before, soo... pretty much ignore my comment above. I need to talk with Jolie about this. 

Perhaps we should do something more akin to how github separates issue titles from issue id/issue url? Does that immediately spark joy/fear/panic?
