### ISSUE TITLE
Update styling for message displayed as user-created kit is being created

### ISSUE THREAD

**Issue by swwalker** [DukeLearningInnovation/kits#393]
6/26/19: Waiting for #406 to be completed to see if the primary cause of this error screen is resolved

### Description ###
I hit save kit and "The course you are attempting to view this page for is still being set up. Please wait while we complete the setup. You will be redirected upon completion" Duke | Log In I let the browser do it's auto refresh thing for about a minute then it moved onto manage membership. Can we style this differently to look like the app instead of ruby native?

### Related Issues ###

- #126 User-created kits

**Comment by LASHirsh** [comment]
@swwalker , it looks like the typo has been resolved already. 

Since people (i.e., first time users) won't know what page they are attempting to view (i.e., roster), consider changing language to:

"We are currently setting up your new custom kit. 
Please wait while we complete the set up."

Reassigning back to @swwalker . (Note: @noahhh previously indicated he'll need @curiousmustard to do a mockup for styling. The same styling will also be applied to the error screen, which currently is also just ruby native styles. See issue #387 .

**Comment by curiousmustard** [comment]
Put this in the linked Error message task, but also putting here. I think this screen would look like my error screen mockup.

> Added a mockup to Zeplin here: https://zpl.io/ankBzzk

**Comment by curiousmustard** [comment]
Here is current snackbar in Test.
<img width="1421" alt="Screen Shot 2019-10-11 at 1 54 10 PM" src="https://user-images.githubusercontent.com/18170417/66673617-ef5cd500-ec2e-11e9-8cfe-0a49ef9b30fd.png">

**Comment by joliet** [comment]
Tested on kits-test with user-created kit MEDICINE 2019-10 SOM Kit and saw the message above in Jen's comment.  I think this issue is resolved.
