### ISSUE TITLE
Remove only bulk add entries that are successful from the bulk add text box

### ISSUE THREAD

**Issue by swwalker** [DukeLearningInnovation/kits#399]
### Description ###
When adding multiple individuals (bulk add), remove only those that have been successfully added to the group.  Currently, all individuals listed are removed from the bulk add text box once the add action is complete, regardless of whether the individual was successfully added or not.  

### Related Issues ###
Found during testing of #383 Bulk add members to kit using netID

**Comment by swwalker** [comment]
@profmikegreene - Noah verified that his fix moved to production.  Please verify it is working as desired.

**Comment by joliet** [comment]
Tested bulk add members to kit with the following steps:

1. Went to kits.duke.edu
2. In kit CROSSLISTED COURSE Sp19, went to View/Edit Roster
3. Clicked the Edit Mode button
4. Clicked on "or bulk add members"
5. In the Add New Members text book added the following netids - hrv, mg287, cl237
6. Received the error below that none of the netids were recognized

![Kits_Bulk_Add_Error](https://user-images.githubusercontent.com/7387760/61055779-3634f780-a3c0-11e9-9958-0629a1e32e0f.png)

The error window needs some improvement with spacing.  It would also be better to have a way to close the window instead of it disappearing automatically.  Users may need to capture the problematic netids to further investigate, especially Alumni who will be using the bulk add feature often.

**Comment by swwalker** [comment]
Errors encountered in adding users related to another open issue (#411) prevented verification that this feature is working as expected.  Remain in Test until confirmed

**Comment by joliet** [comment]
Tested on kits-test with user-created kit TRINITY 100-101: Physics research group.  Only users who were added disappeared from the text box.  Users who could not be added remained in the box and I received an error message that the remaining did not have accounts and could not be added.
