### ISSUE TITLE
When creating a new kit, return user to My Kits page

### ISSUE THREAD

**Issue by swwalker** [DukeLearningInnovation/kits#417]
### Description ###
When a new kit is being created, the current flow brings the user to the View Roster page, which assumes all users will want to immediately add individuals to the roster.  However, a user may wish to provision resources first, or create multiple kit shells.  Changing the flow to return to the My Kits page will allow for these differences in desired workflow.

### Related Issues ###
#126 - User-created kits
#406 - Grouper slowdown

**Comment by noahhh** [comment]
@LASHirsh @joliet should there be a popup message that displays when returning to the My Kits page?  Even something small like 'Course was created!' to show it was a success

**Comment by LASHirsh** [comment]
@noahhh , Yep! Although we should use "kit" instead of "course". ;-) 

Would also be great (although I don't know whether this is feasible or how difficult it would be) if when you return to My Kits, you are automatically brought to the part of the page/row where your new kit is and it's highlighted (fading highlight like we use on roster management)

**Comment by joliet** [comment]
I created two user-created kits today - SANFORD 2019-11 Sanford Test Kit and FUQUA 2019-11
Executive MBA Resources.  In both cases, I was taken back to the My Kits page after creating the kit and not the manage membership page.
