### ISSUE TITLE
Deleting an app doesn't work in Kits-test

### ISSUE THREAD

**Issue by hrvalli** [DukeLearningInnovation/kits#421]
**Describe the bug**
When in Kits-test, I added apps to a kit and then tried to delete one of those apps. When I clicked on the kebob, selected "delete" and clicked on one of the trashcan icons to delete the app it was on, nothing happened.

**To Reproduce**
1. Go to 'kits-test'
2. Click on 'the kebob of a kit with apps'
3. Scroll down to 'delete'
4. Click on the trashcan icon on one of the apps
5. Be disappointed when the app isn't deleted. 

**Expected behavior**
I expect the app I'm trying to delete to disappear from the kit card. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: iOS 10.12.6
 - Browser safari
 - Version 12.1.2

**Smartphone (please complete the following information):**
 - not applicable

**Additional context**
 See issue #359

**Comment by LASHirsh** [comment]
@hrvalli , this is a definite usability issue. 

(I'm not sure it's a bug in that I don't think the code is set up to work the way you are expecting, but it obviously appears to end users to be a bug!) ...I actually just tried clicking the trashcan too and it was only when nothing happened, I remembered I had to click the app icon, itself. 

I think there might already be an enhancement issue for this @joliet ? (i.e., to make it so that the user can click either the trash icon or the actual app icon to delete the app)

**Comment by noahhh** [comment]
I remember Will talked about this at one point.  He had to remove the ability to click the trash icon because for some reason that was making the icon off-center.   It could be worth talking to him again.

**Comment by swwalker** [comment]
Closed - already reported in #359
