### ISSUE TITLE
Disallow membership editing in Sakai for Combined Kits

### ISSUE THREAD

**Issue by swwalker** [DukeLearningInnovation/kits#458]
**Describe the bug**
Reported by Liz Wendland:
If a user edits the membership for a Combined Kit in Sakai, they should edit at the sub-kit (individual kit) level.  Because Sakai currently interfaces with Tookits (not Kits) and combining Kits is a feature only available in Kits, allowing membership editing in Sakai will cause problems until the Sakai/Kits interface is completed.

**Expected behavior**
Open the roster management page from Kits in an iFrame in Sakai.  This should be the behavior for both combined course as well as stand alone courses.

**Comment by joliet** [comment]
This is working, but it takes the user to the main Kits page instead of directly to the roster for editing.  Can we change that @ewendland23 ?

We need a better feedback message for the user on what is happening.  Marking for crux and including a screenshot of the existing message.

<img width="579" alt="Error_Edit_in_Kits" src="https://user-images.githubusercontent.com/7387760/72638641-d9e3ff00-3931-11ea-9f6f-d7d747a88578.png">

It would be better not to use the word 'error'.  This is working as designed.  We'll need to think about how to communicate this to users before putting this into production.

**Comment by ewendland23** [comment]
@joliet  - it brings you to the Roster edit page if you have rights to that page.  Lots of times that won't be the case because Roster editing in Kits is different than in Toolkits. (No Delegates for example)

**Comment by curiousmustard** [comment]
Updated styling and message text is in Zeplin here: https://zpl.io/brXZZRr
