### ISSUE TITLE
Setting Sakai sites to template type / template name

### ISSUE THREAD

**Issue by chrislorch** [DukeLearningInnovation/kits#463]
Related to #354 
Setting Sakai sites to template type / template name
This one's especially weird / serious (see screenshot of Worksite setup > Create site)

Course Title: Duke Nursing Course Template
Toolkit Title: NURSING 811 - 01: Oncology Specialty I
Site ID: NURSING.811.01.Sp20

<img width="572" alt="Sakai___Home___Worksite_Setup" src="https://user-images.githubusercontent.com/5098070/68135476-b5ab8100-fef1-11e9-90ab-174341fa553c.png">

**Comment by joliet** [comment]
In testing this previously, I have not been able to identify the Toolkits batch create as the source of this problem.  I have been able to replicate this in Worksite Setup in Sakai.  I believe the source of this problem is with Sakai and not Toolkits.  I have tried multiple times to resolve this with Longsight without success (difficult to replicate/troubleshoot).
