### ISSUE TITLE
Distinguish between activities performed in Toolkits vs Kits

### ISSUE THREAD

**Issue by swwalker** [DukeLearningInnovation/kits#477]
In order to monitor the transition from Toolkits to Kits, the activity logs should identify whether an activity was initiated through the Toolkits user interface or through the Kits user interface

**Related Issues**
#476 Collect activity data in Kits for analytics

**Questions**

**Assumptions**

**Hypotheses**

**Comment by noahhh** [comment]
Hi @joliet ,

I've moved this ticket, along with #476 to test.

I would suggest testing by using https://kits-test.oit.duke.edu/activity_log to verify that Activities are created for the actions we discussed.

The text ' (by delegate nh118@duke.edu)' will show up if you are impersonating - but you may need to clear your cache or impersonate and then exit impersonation right now for it to clear that session information, otherwise it will display that even if you are not impersonating.

All actions I've logged in new Kits are prefaced with the text 'Kits: ....', where old toolkits actions are not.

**Comment by joliet** [comment]
This looks good so far @noahhh.  I just logged into Kits as Bridgette Hard and all the the kits populated for all of her Spring 2020 psychology courses.  But log activity log doesn't show that those groups were created by Kits.  That's something we'll want to track as well.  Thanks!

**Comment by noahhh** [comment]
Hi @joliet ,

Thanks for catching that - I don't have any non-custom courses in local dev so I missed that one.  I have updated kits-test so it should capture and say 'Kits: Course Created'

Thanks,
Noah

**Comment by joliet** [comment]
The above is related to issue Track the origin of Toolkits/Kits being created - https://github.com/DukeLearningInnovation/kits/issues/460

Re-tested by masquerading as Stacy Tantum and Genevieve Lipp and their course Toolkits/Kits showed as being created in Kits in the activity log.

**Comment by joliet** [comment]
Re-opening for more testing.
