### ISSUE TITLE
learn.duke service owners have the ability to display blog-like entries, service updates, or links to other useful resources because learn.duke users will find value in finding this info here

### ISSUE THREAD

**Issue by profmikegreene** [DukeLearningInnovation/kits#54]

**Comment by JustinJohnsen** [comment]
I think we'd want to be very cautious, especially early on, not to spam users (especially students) with content that is not directly useful to them. Since it would be hard to gauge what would be useful to everyone, or tailor content to particular users, I would image this as more of a subtle link to options at the bottom of the page (like in GitHub for Terms, Privacy, Security, Status, Help, Blog, etc...).

**Comment by profmikegreene** [comment]
We can append a changelog to the about page, closing.
