### ISSUE TITLE
Since a reference group is auto-generated for every roster, is a course card auto-generated or do we wait for faculty to initiate a create process?

### ISSUE THREAD

**Issue by LASHirsh** [DukeLearningInnovation/kits#73]
(copied from [Questions](https://github.com/DukeLearningInnovation/learn.duke/blob/master/courses/readme.md#questions-for-courses) on /courses)

My current thinking is to have the card auto-generated (why force faculty to take an extra step?), unless this creates issues for merging rosters/cross-listed courses.

**Comment by JustinJohnsen** [comment]
The auto-generated card will need to be visible and recognizable to instructors so that they don't go and create their own version of the course card causing duplication and confusion.

**Comment by JustinJohnsen** [comment]
Initially we may not need to offer card creation options, if we are scoping to only courses and we auto-generate all of those cards. Later we'll probably need to have this capability, though.

**Comment by profmikegreene** [comment]
My vote is for making the creation of course cards a single click and super great UX and not auto-creating. Auto-creating creates waste in our DB and in the user’s UI. We also have to define rules around what to and not to auto-create, are we auto-creating cards for clinical labs or independent study courses?

**Comment by profmikegreene** [comment]
- [ ] create user story for this

**Comment by swwalker** [comment]
Because this question refers to course communities, and because the decision has been made to allow students to add custom urls for any of their communities regardless of whether or not the faculty member has used toolkits or the kits app to setup tools for the course, a course card will need to be available for all current courses as soon as enrollment occurs.  Course cards should be auto-generated based on the available data from the source system.
