### ISSUE TITLE
Do we build in a rating system for each app?

### ISSUE THREAD

**Issue by LASHirsh** [DukeLearningInnovation/kits#76]
(copied from [Questions](https://github.com/DukeLearningInnovation/learn.duke/blob/master/apps/readme.md#questions-on-apps) on /apps)

I would say not as part of a first version.

**Comment by JustinJohnsen** [comment]
Definitely not in the first, but maybe not ever? It feels like too many things in our lives already insist on knowing if we give it a thumbs up or 5 stars. I wouldn't feel good about seeing a dozen of those on a student-facing course site as well. Maybe a combo of usage metrics and flagged feedback can give us what we'd need?

Maybe if there are times we need to make a keep/drop call with an app, we could have some kind of targeted (rating?) inquiry just for that app just for a limited time, to help provide more information.

**Comment by profmikegreene** [comment]
Perhaps part of our app management process is x months before contract renewal we review usage, if there’s not some type of growth, we do a targeted campaign.

My worry with a rating system, if you’re using the app, you probably don’t want it ripped away from you so you’ll answer thumbs up and no one else will answer, giving us a false sense of need. 

If we can establish good usage metrics that show what disciplines use the tools, we can create requirements around what OIT enterprise licensing vs learning innovation vs individual schools/departments pay for. If over time, usage shows that only the one discipline uses an app, we have a discussion with that discipline/school and the vendor about a better fitting contract and don’t have to pull the app out of /apps because it didn’t meet some growth metric.

We can facilitate that whole process as a service if that’s what we think should happen.
