### ISSUE TITLE
What is a good metric for 'used' in a course? The existence of a tool in Sakai means nothing when that tool is part of the template. 2 create.tool events or existence of 1 item in the sakai-db?

### ISSUE THREAD

**Issue by LASHirsh** [DukeLearningInnovation/kits#77]
(copied from [Questions](https://github.com/DukeLearningInnovation/learn.duke/blob/master/apps/readme.md#questions-on-apps) on /apps)

**Comment by JustinJohnsen** [comment]
If I understand this right, then the suggestions is that provisioning a tool/app(/course?) does not mean it is 'used', but perhaps adding a resource to it does. I imagine there is some basic set of actions just beyond provisioning that we might use to track whether an app or course card have been 'used'. Those might be different across apps, in that a video player app won't have the exact same next actions as an announcement app.

**Comment by profmikegreene** [comment]
Correct @JustinJohnsen declaring different metrics for provisioning vs usage and if possible using the same definition across all tools. I suggest a faculty create event and student read event as starting points. If we find that every tool has a student interact event, I would suggest using that instead of student read.

- create apps/events.md to begin cataloging events provided

**Comment by profmikegreene** [comment]
This has been rolled into #203 or #211 future discussion should happen there.
